import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import customersRouter from "./customers";
import suppliersRouter from "./suppliers";
import salesRouter from "./sales";
import purchasesRouter from "./purchases";
import mutationsRouter from "./mutations";
import receivablesRouter from "./receivables";
import payablesRouter from "./payables";
import cashbookRouter from "./cashbook";
import reportsRouter from "./reports";
import paymentMethodsRouter from "./payment-methods";
import unitsRouter from "./units";
import usersRouter from "./users";
import notificationsRouter from "./notifications";
import { settingsRouter } from "./settings";
import returnsRouter from "./returns";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(suppliersRouter);
router.use(salesRouter);
router.use(purchasesRouter);
router.use(mutationsRouter);
router.use(receivablesRouter);
router.use(payablesRouter);
router.use(cashbookRouter);
router.use(reportsRouter);
router.use(paymentMethodsRouter);
router.use(unitsRouter);
router.use(returnsRouter);

router.use("/users", usersRouter);
router.use("/notifications", notificationsRouter);
router.use("/settings", settingsRouter);
export default router;
